# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/lowlighter/metrics/blob/master/source/templates/classic/README.md
      - name: Classic template
        uses: lowlighter/metrics@latest
        with:
          filename: static/metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes

      # https://github.com/lowlighter/metrics/blob/master/source/plugins/calendar/README.md
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_calendar: yes
          plugin_calendar_limit: -1
